%====================== estimationwithFB.m ===============================
% Program evaluates some parameters from the signals
% located in the directory directorysignals.
% The signals correspond to the pair of sensors
% SUT/SREF during a given duration T, typically 48 hours.
%
% The evaluated parameters consist of the ratios, the STDs, etc
% They are obtained by averaging on the period T.
% They are saved in directoryresults.
%=========================================================================
%
%==================== Warning ===============
% we have observed huge outliers/problems in the following files:
% ihc==1, date==2015/08/09 , shift between the 2 signals for the full
% duration
% ihc==1, date==2015/10/07 ,from sample index 2.4e6
% ihc==1, date==2015/10/09 ,from sample index 2.4e6
% ihc==2, date==2015/08/07 ,from sample index 2.4e6
% ihc==2, date==2015/10/05 ,from sample index 2.4e6
% ihc==5, date==2015/10/05
% ihc==6, date==2015/10/07
% ihc==8, date==2015/10/07 , from sample index 2.5e6
% in this version we remove them
%
%=========================================================================

clear
addpath ZZtoolbox/

%=====================
MSCthreshold     = 0.98;
FLAGsavesmall    = 1;
Fs_Hz            = 20;
%=====================
%=== directory of input signals
directorysignals    = '../../../AAdataI26calib/';
%=== directory of output results (huge records)
% if FLAGsavesmall=1
directoryresults    = sprintf('AAresultsLite%i',fix(MSCthreshold*100));

%============== load the filter bank characteristics =====================
%  the useful variable is FILTERCHARACT
%======
% if generated by geneFB.m, use LOAD; if it is a .m program use RUN
% filtercharactfilename = 'filtercharacteristics/filtercharacteristics';
%cmdloadfilter        = sprintf('load(''%s'')',filtercharactfilename);
filtercharactfilename = 'filtercharacteristics/filtercharacteristics1.m';
cmdloadfilter         = sprintf('run(''%s'')',filtercharactfilename);
eval(cmdloadfilter);
%=====================
Pfilter                = length(filtercharact);
filterbank             = cell(Pfilter,1);
nbfrequenciesbyband    = 10;
allfreqsinfilters_Hz   = zeros(nbfrequenciesbyband,Pfilter);
windshape              = cell(Pfilter,1);
for ifilter = 1:Pfilter
    flow    = filtercharact(ifilter).Wlow_Hz/Fs_Hz;
    fhigh   = filtercharact(ifilter).Whigh_Hz/Fs_Hz;
    fname   = filtercharact(ifilter).designname;
    forder  = filtercharact(ifilter).Norder;
    allfreqsinfilters_Hz(:,ifilter) =linspace( ...
        filtercharact(ifilter).Wlow_Hz,...
        filtercharact(ifilter).Whigh_Hz,...
        nbfrequenciesbyband);
    switch fname
        case 'fir1'
            fdesign = sprintf('filnum = %s(%i,[%5.8f,%5.8f]);',...
                fname,forder,2*flow,2*fhigh);
            filden = 1;
        case 'butter'
            fdesign = sprintf('[filnum,filden] = %s(%i,[%5.8f %5.8f]);',...
                fname,forder,2*flow,2*fhigh);
        case 'cheby1'
            fdesign = sprintf('[filnum,filden] = %s(%i,%i,[%5.8f %5.8f]);',...
                fname,forder,0.02,2*flow,2*fhigh);
    end
    windowshapename = filtercharact(ifilter).windowshape;
    SCPperiod_sec   = filtercharact(ifilter).SCPperiod_sec;
    ratioDFT2SCP    = filtercharact(ifilter).ratioDFT2SCP;
    lengthDFT       = fix(SCPperiod_sec*Fs_Hz/ratioDFT2SCP);
    
    switch windowshapename
        case 'hann'
            windshape{ifilter} = hann(lengthDFT,'periodic');
    end
    eval(fdesign);
    filterbank{ifilter}.num = filnum;
    filterbank{ifilter}.den = filden;
end
ihc   = 1;
%===================== read data =========================
fileswithdotmat   = dir(sprintf('%ss%i/s%iy*.mat',...
    directorysignals,ihc,ihc));
nbmats             = length(fileswithdotmat);
ifile              = input(sprintf('select a number between 1 and %i : ',nbmats));

%====== Useful evaluated parameters for general purposes
allfrqsPfilters              = zeros(Pfilter*nbfrequenciesbyband,1);
allRatioSupPfilters          = zeros(Pfilter*nbfrequenciesbyband,1);
allSTDmodRatioSupPfilters    = zeros(Pfilter*nbfrequenciesbyband,1);
allSTDphaseRatioSupPfilters  = zeros(Pfilter*nbfrequenciesbyband,1);

allmeanMSCcstPfilters        = zeros(Pfilter*nbfrequenciesbyband,1);
nbofvaluesoverthreshold      = zeros(Pfilter*nbfrequenciesbyband,1);
%==================================================
fullfilename_i      = fileswithdotmat(ifile).name;
dotlocation         = strfind(fullfilename_i,'.');
underscorelocation  = strfind(fullfilename_i,'_');
filenameonly        = fullfilename_i(...
    setdiff(1:dotlocation-1,...
    underscorelocation));
commandload         = sprintf('load %ss%i/%s',...
    directorysignals,ihc,fullfilename_i);
eval(commandload)

Ntotal = size(signals_centered,1);

date_i = sprintf('%s/%s/%s',fullfilename_i(7:10),...
    fullfilename_i(16:17),fullfilename_i(21:22));

%============================================
%============================================
% filtering the signals
%============================================
[Nsignals,nbsignals] = size(signals_centered);
sigout               = zeros(Nsignals,nbsignals,Pfilter);
for ifilter = 1:Pfilter
    filnum = filterbank{ifilter}.num;
    filden = filterbank{ifilter}.den;
    sigout(:,:,ifilter) = filter(filnum,filden,signals_centered);
end
%============================================
%============================================
% in each band we perform DFTs then SCPs
tabRsup   = cell(Pfilter,1);
% tabMSC    = cell(Pfilter,1);

for ifilter = 1:Pfilter
    SCPperiod_sec   = filtercharact(ifilter).SCPperiod_sec;
    overlapDFT      = filtercharact(ifilter).overlapDFT;
    ratioDFT2SCP    = filtercharact(ifilter).ratioDFT2SCP;
    lengthDFT       = fix(SCPperiod_sec*Fs_Hz/ratioDFT2SCP);
    lengthSCP       = fix(SCPperiod_sec*Fs_Hz);
    DFTshift        = fix((1-overlapDFT)*lengthDFT);
    NSCPwindows     = fix(Nsignals/SCPperiod_sec/Fs_Hz);
    sigauxW         = zeros(lengthDFT,2);
    listindex       = (0:lengthDFT-1)';
    
    SCP_ifreq11     = zeros(nbfrequenciesbyband,NSCPwindows-1);
    SCP_ifreq22     = zeros(nbfrequenciesbyband,NSCPwindows-1);
    SCP_ifreq12     = zeros(nbfrequenciesbyband,NSCPwindows-1);
    
    for iwindowSCP  = 1:NSCPwindows-1
        id0   = (iwindowSCP-1)*lengthSCP;
        id1   = 0;
        cpDFT = 0;
        while id1<id0+lengthSCP-lengthDFT
            cpDFT  = cpDFT+1;
            id1    = id0 + (cpDFT-1)*DFTshift+1;
            id2    = id1+lengthDFT-1;
            sigaux = sigout(id1:id2,:);
            sigauxW(:,1) = sigaux(:,2) .* windshape{ifilter};
            sigauxW(:,2) = sigaux(:,1) .* windshape{ifilter};
            for ifreq = 1:nbfrequenciesbyband
                fq_aux   = allfreqsinfilters_Hz(ifreq,ifilter)/Fs_Hz;
                EXPVect  = exp(-2j*pi*fq_aux*listindex);
                X_ifreq1 = sum(sigauxW(:,1) .* EXPVect);
                X_ifreq2 = sum(sigauxW(:,2) .* EXPVect);
                SCP_ifreq11(ifreq,iwindowSCP) = SCP_ifreq11(ifreq,iwindowSCP) + ...
                    X_ifreq1 .* conj(X_ifreq1);
                SCP_ifreq22(ifreq,iwindowSCP) = SCP_ifreq22(ifreq,iwindowSCP) + ...
                    X_ifreq2 .* conj(X_ifreq2);
                SCP_ifreq12(ifreq,iwindowSCP) = SCP_ifreq12(ifreq,iwindowSCP) + ...
                    X_ifreq1 .* conj(X_ifreq2);
            end
        end
    end
    tabRsup_ifilter  = SCP_ifreq11 ./ SCP_ifreq12;
    tabMSC_ifilter   = (abs(SCP_ifreq12) .^2) ./ (SCP_ifreq11 .* SCP_ifreq22);
    tabRsup_ifilter_overTH = NaN(size(tabRsup_ifilter));
    tabRsup_ifilter_overTH(tabMSC_ifilter>0.98) = tabRsup_ifilter(tabMSC_ifilter>0.98);
    tabRsup{ifilter} = tabRsup_ifilter_overTH;
end
R = zeros(nbfrequenciesbyband,Pfilter);
for  ifilter = 1:Pfilter
    R(:,ifilter) = nanmean([tabRsup{ifilter}],2);
end


