%====================== plotsignalclick.m =============================
clear
allcolors = ['b.';'r.';'m.';'c.';'g.';'k.';'rx';'yx';'mx';'rx';'kx';...
    'c.';'k.';'r.';'c.';'m.';'g.';'b.';'k.';'r.';'c.';'m.';'g.';'k.'];

addpath ../ZZtoolbox/
%============== load the filter bank characteristics =======================
%  the useful variable is FILTERCHARACT
%======
% if generated by geneFB.m, use LOAD; if it is a .m program use RUN
% filtercharactfilename = 'filtercharacteristics/filtercharacteristics';
% cmdloadcharact        = sprintf('load(''%s'')',filtercharactfilename);
filtercharactfilename = '../filtercharacteristics/filtercharacteristics1.m';
cmdloadcharact        = sprintf('run(''%s'')',filtercharactfilename);
%======
eval(cmdloadcharact);
Pfilter = length(filtercharact);
%============ Warning =======================
%============================================
%============================================
%============================================
%============================================
% if and(ihc==1,ifile==63)
% if and(ihc==2,ifile==33)
%     signals_centered = signals_centered(1:2.4e6,:);
% end
% if and(ihc==2,ifile==67)
%     signals_centered = signals_centered([1:0.5e6 1e6:idScMin-1],:);
% end
% if and(ihc==5,ifile==62)
%     signals_centered = signals_centered(1:2.4e6,:);
% end
% if and(ihc==6,ifile==63)
%     signals_centered = signals_centered(1:2.14e6,:);
% end
% if and(ihc==8,ifile==63)
%     signals_centered = signals_centered(1:2.5e6,:);
% end
%============================================
%============================================
%============================================
%===================== displayapairofdays.m ================
directorysave2daysignals  = '../../../../AAdataI26calib/';
%===================== read data =========================
% nbmats                       = length(fileswithdotmat);
for ihc   = 4
    fileswithdotmat     = dir(sprintf('%ss%i/s%iy*.mat', ...
        directorysave2daysignals,ihc,ihc));
    nbmats = length(fileswithdotmat);
    for ifile = 66%1:nbmats,ifile    
        fullfilename_i      = fileswithdotmat(ifile).name;
        dotlocation         = strfind(fullfilename_i,'.');
        underscorelocation  = strfind(fullfilename_i,'_');
        filenameonly        = fullfilename_i(setdiff(1:dotlocation-1,underscorelocation));
        commandload         = sprintf('load %ss%i/%s',directorysave2daysignals,...
            ihc,fullfilename_i);
        date_ii = sprintf('%s/%s/%s',filenameonly(7:10),filenameonly(16:17),filenameonly(21:22));
        eval(commandload)
        tps_sec = (0:size(signals_centered,1)-1)/Fs_Hz;

        subplot(311)
        plot(tps_sec/3600,signals_centered(:,1))
        subplot(312)
        plot(tps_sec/3600,signals_centered(:,2))
        subplot(313)
        plot(tps_sec/3600,signals_centered)
    end
end