%====================== plotsignalclick.m =============================
clear
allcolors = ['b.';'r.';'m.';'c.';'g.';'k.';'rx';'yx';'mx';'rx';'kx';...
    'c.';'k.';'r.';'c.';'m.';'g.';'b.';'k.';'r.';'c.';'m.';'g.';'k.'];

addpath ../ZZtoolbox/
%============== load the filter bank characteristics =======================
%  the useful variable is FILTERCHARACT
%======
% if generated by geneFB.m, use LOAD; if it is a .m program use RUN
% filtercharactfilename = 'filtercharacteristics/filtercharacteristics';
% cmdloadcharact        = sprintf('load(''%s'')',filtercharactfilename);
filtercharactfilename = '../filtercharacteristics/filtercharacteristics1.m';
cmdloadcharact        = sprintf('run(''%s'')',filtercharactfilename);
%======
eval(cmdloadcharact);
Pfilter = length(filtercharact);
%============ Warning =======================
%============================================
%============================================
%============================================
%============================================
% if and(ihc==2,ifile==33)
%     signals_centered = signals_centered(1:2.4e6,:);
% end
% if and(ihc==2,ifile==62)
%     signals_centered = signals_centered([1:0.5e6 1e6:idScMin-1],:);
% end
% if and(ihc==5,ifile==62)
%     signals_centered = signals_centered(1:2.4e6,:);
% end
% if and(ihc==6,ifile==63)
%     signals_centered = signals_centered(1:2.14e6,:);
% end
% if and(ihc==8,ifile==63)
%     signals_centered = signals_centered(1:2.5e6,:);
% end
%============================================
%============================================
%============================================
%=====================
MSCthreshold = 0.98;
%=====================
directorysave2daysignals  = '../AAsignals/';
%===================== read data =========================
% nbmats                       = length(fileswithdotmat);

%==================================================
for ifile = 27:50,
    signals = cell(2,1);
    for ihc   = [1,2]
        fileswithdotmat     = dir(sprintf('%ss%i/year*.mat',directorysave2daysignals,ihc));

        fullfilename_i      = fileswithdotmat(ifile).name;
        dotlocation         = strfind(fullfilename_i,'.');
        underscorelocation  = strfind(fullfilename_i,'_');
        filenameonly        = fullfilename_i(setdiff(1:dotlocation-1,underscorelocation));
        commandload         = sprintf('load %ss%i/%s',directorysave2daysignals,...
            ihc,fullfilename_i);
        eval(commandload)
        signals{ihc} = signals_centered;
    end
    
    
    % [SUTs, filteredsignals, allfrqsFFT_Hz, alltimes_sec, filterbank] = ...
    %     fbankanalysis(signals_centered,...
    %     filtercharact,Fs_Hz,MSCthreshold);
    % %============================================
    % P       = length(SUTs);
    % idipinf = zeros(P,1);
    % idipsup = zeros(P,1);
    % for ip=1:P
    %     idipinf(ip) = SUTs(ip).indexinsidefreqband(1);
    %     idipsup(ip) = SUTs(ip).indexinsidefreqband(2);
    % end
    % displayhours = fix(size(signals_centered,1)/Fs_Hz/3600);
    % for ip=1:P
    %     [nbfrqs,nbtimeslots] = size(SUTs(ip).allMSCs.tabcst((idipinf(ip):idipsup(ip)),:));
    %     allfrqs_ip = allfrqsFFT_Hz{ip}(idipinf(ip):idipsup(ip));
    %
    % end
    %========= display signals ===
    
    
    %     locations(:,1) = decrac(signals_centered(:,1));
    %     locations(:,2) = decrac(signals_centered(:,2));
    %
    %%
    
    for is=1:2
        for io=1:2
        subplot(4,1,2*(is-1)+io)
        plot(signals{is}(:,io))
        end
    end
    pause
    
    % set(gca,'xlim',[0 displayhours])
    set(gca,'ylim',[-12 12])
    set(gca,'fontname','times','fontsize',10)
    xlabel('hours','fontname','times','fontsize',10)
    
    
    HorizontalSize = 16;
    VerticalSize   = 14;
    set(gcf,'units','centimeters');
    set(gcf,'paperunits','centimeters');
    set(gcf,'PaperType','a3');
    set(gcf,'position',[0 5 HorizontalSize VerticalSize]);
    set(gcf,'position',[0 5 HorizontalSize VerticalSize]);
    set(gcf,'paperposition',[0 0 HorizontalSize VerticalSize]);
    set(gcf,'color', [1,1,0.92]);
    set(gcf, 'InvertHardCopy', 'off');
    
    printdirectory  = ' ../../figures/';
    
    fileprint = sprintf('%sclickdetails%iyear%sday%saboveTH.eps',...
        printdirectory,ihc,filenameonly(6:9),filenameonly(11:13));
    
    fileprintepscmd = sprintf('print -depsc -loose %s',fileprint);
    fileeps2pdfcmd  = sprintf('!/Library/TeX/texbin/epstopdf %s',fileprint);
    filermcmd       = sprintf('!rm %s',fileprint);
    
    %
    %         eval(fileprintepscmd)
    %         eval(fileeps2pdfcmd)
    %         eval(filermcmd)
end
%============================ END =========================================